export enum AuthEventType {
  REGISTER = 'REGISTER',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  TOKEN_ROTATED = 'TOKEN_ROTATED',
  TOKEN_REUSE_DETECTED = 'TOKEN_REUSE_DETECTED',
  LOGOUT = 'LOGOUT',
  LOGOUT_ALL = 'LOGOUT_ALL',
}
